# Generated by Django 3.0.4 on 2020-03-15 09:52

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0002_auto_20200315_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 9, 52, 18, 836170, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 9, 52, 18, 805275, tzinfo=utc)),
        ),
    ]
