# Generated by Django 3.0.4 on 2020-03-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0005_auto_20200315_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
