# Generated by Django 3.0.4 on 2020-03-15 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0007_auto_20200315_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_id',
            new_name='author',
        ),
    ]
