# Generated by Django 3.0.4 on 2020-03-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0009_auto_20200322_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
