# Generated by Django 3.0.4 on 2020-05-13 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0010_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                   to='forum.User')),
                ('language', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
    ]
